// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export const configration = {
  aws_appsync_graphqlEndpoint:
    "https://syn3vddvf5durmyoighbskxsgu.appsync-api.us-east-2.amazonaws.com/graphql",
  aws_appsync_region: "us-east-2",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-erswtpxirzg2hkfvkxtbri6roi",
};
